# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.FloatField(default=None)),
                ('theta', models.FloatField(default=None)),
                ('x', models.FloatField(default=None)),
                ('y', models.FloatField(default=None)),
            ],
        ),
    ]
