# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htvector',
            name='m',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='htvector',
            name='theta',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='htvector',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='htvector',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
    ]
