# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physics', '0002_auto_20170521_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='htvector',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
