# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Physics', '0003_htvector_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(db_index=True, max_length=240)),
                ('value', models.FloatField(db_index=True)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HTExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('T', 'Tipler'), ('H', 'Halliday')], max_length=1)),
                ('volume', models.IntegerField(blank=True, choices=[(1, 'Volume 1'), (2, 'Volume 2'), (3, 'Volume 3'), (4, 'Volume 4')])),
                ('chapter', models.IntegerField(blank=True, default=None)),
                ('page', models.IntegerField(blank=True, default=None)),
                ('exercise', models.CharField(blank=True, default=None, max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='htdata',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physics.HTExercise'),
        ),
    ]
