# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTransistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrode_in', models.IntegerField(default=0)),
                ('electrode_out', models.IntegerField(default=0)),
                ('gate', models.IntegerField(default=0)),
            ],
        ),
    ]
