# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cctransistor',
            old_name='gate',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='cctransistor',
            old_name='electrode_in',
            new_name='collector',
        ),
        migrations.RenameField(
            model_name='cctransistor',
            old_name='electrode_out',
            new_name='emitter',
        ),
    ]
