# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0002_auto_20170623_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=0)),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CCCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CCConection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('transistor1field', models.CharField(max_length=10)),
                ('transistor2field', models.CharField(max_length=10)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.CCCircuit')),
                ('transistor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_from', to='Computer.CCTransistor')),
                ('transistor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_to', to='Computer.CCTransistor')),
            ],
        ),
    ]
