# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0003_ccbattery_cccircuit_ccconection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cccircuit',
            name='instate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cccircuit',
            name='outstate',
            field=models.IntegerField(default=0),
        ),
    ]
