# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0004_auto_20170624_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCConection',
            new_name='CCConnection',
        ),
    ]
